const fs = require('fs');
const path = require('path');

const brandFile = process.argv[2] || 'brand.json';
const brandPath = path.join(__dirname, brandFile);

if (!fs.existsSync(brandPath)) {
    console.error(`Branding file not found: ${brandFile}`);
    process.exit(1);
}

const brand = JSON.parse(fs.readFileSync(brandPath, 'utf8'));

// 1. Update manifest.json
const manifestPath = path.join(__dirname, 'manifest.json');
let manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

manifest.name = brand.name;
manifest.description = brand.description;

if (brand.manifestIcon128) {
    manifest.icons = {
        "128": `assets/${brand.manifestIcon128}`
    };
} else {
    delete manifest.icons;
}

const configPath = path.join(__dirname, 'config.json');
if (fs.existsSync(configPath)) {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    const matches = config.supportedDomains.map(d => `*://${d}/*`);
    if (manifest.content_scripts) {
        manifest.content_scripts.forEach(cs => {
            cs.matches = matches;
        });
    }
    const configJsContent = `// Auto-generated by apply_brand.js from config.json\nconst SpiimaskConfig = ${JSON.stringify(config, null, 2)};\n`;
    fs.writeFileSync(path.join(__dirname, 'config.js'), configJsContent);
    console.log(`Generated config.js and updated manifest matches.`);
}

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
console.log(`Updated manifest.json with brand: ${brand.name}`);

// 2. Generate brand.js for the content and core scripts
const brandJsPath = path.join(__dirname, 'brand.js');
const brandJsContent = `// Auto-generated by apply_brand.js from ${brandFile}\nwindow.SpiimaskBrand = ${JSON.stringify(brand, null, 2)};\n`;

fs.writeFileSync(brandJsPath, brandJsContent);
console.log(`Generated brand.js for extension scripts.`);
